module.exports = {
    
    /* PIECES */
    TOGGLE_EDIT: "TOGGLE_EDIT",
    TOGGLE_HIGHLIGHT: "TOGGLE_HIGHLIGHT",
    
    PIECE_UPDATE: "PIECE_UPDATE",
    PIECE_ADD: "PIECE_ADD",

    I18N_INIT: "I18N_INIT",
    I18N_FIND: "I18N_FIND",
    I18N_ADD: "I18N_ADD",
    I18N_SET_ELEMENTS: "I18N_SET_ELEMENTS",

    PIECE_FETCHING: "PIECE_FETCHING",
    PIECE_FETCHED: "PIECE_FETCHED",
    PIECE_FETCHING_FAILED: "PIECE_FETCHING_FAILED",
    PIECE_FETCHING_ERROR: "PIECE_FETCHING_ERROR",

    PIECE_SAVING: "PIECE_SAVING",
    PIECE_SAVED: "PIECE_SAVED",
    PIECE_SAVING_FAILED: "PIECE_SAVING_FAILED",
    SET_PIECE_CURRENT_SOURCE_ID: "SET_PIECE_CURRENT_SOURCE_ID",

    /* PAGES */
    PAGES_SET_CURRENT_INDEX: "PAGES_SET_CURRENT_INDEX",
    PAGES_GET_STARTED: "PAGES_GET_STARTED",
    PAGES_GET_FINISHED: "PAGES_GET_FINISHED",
    PAGES_GET_ERROR: "PAGES_GET_ERROR",

    PAGE_START_CREATING: "PAGE_START_CREATING",
    PAGE_CANCEL_CREATING: "PAGE_CANCEL_CREATING",
    PAGE_UPDATE: "PAGE_UPDATE",
    PAGE_DATA_UPDATE: "PAGE_DATA_UPDATE",
    PAGE_DATA_FIELDS_UPDATE: "PAGE_DATA_FIELDS_UPDATE",
    PAGE_DATA_FIELDS_SET: "PAGE_DATA_FIELDS_SET",
    
    PAGE_ADD: "PAGE_ADD",

    PAGE_SAVING: "PAGE_SAVING",
    PAGE_SAVE_ERROR: "PAGE_SAVE_ERROR",
    PAGE_SAVED: "PAGE_SAVED",

    PAGE_DELETING: "PAGE_DELETING",
    PAGE_DELETE_ERROR: "PAGE_DELETE_ERROR",
    PAGE_DELETED: "PAGE_DELETED",

    PAGES_GET_LAYOUTS_STARTED: "PAGES_GET_LAYOUTS_STARTED",
    PAGES_GET_LAYOUTS_FINISHED: "PAGES_GET_LAYOUTS_FINISHED",
    PAGES_GET_LAYOUTS_ERROR: "PAGES_GET_LAYOUTS_ERROR",

    /* GLOBAL */
    SHOW_MESSAGE: "SHOW_MESSAGE"
};