module.exports = {
    TOGGLE_EDIT: "TOGGLE_EDIT",
    TOGGLE_HIGHLIGHT: "TOGGLE_HIGHLIGHT",
    
    PIECE_UPDATE: "PIECE_UPDATE",
    PIECE_ADD: "PIECE_ADD",

    PIECE_GETTING: "PIECE_GETTING",
    PIECE_GOT: "PIECE_GOT",
    PIECE_GETTING_FAILED: "PIECE_GETTING_FAILED",

    PIECE_SAVING: "PIECE_SAVING",
    PIECE_SAVED: "PIECE_SAVED",
    PIECE_SAVING_FAILED: "PIECE_SAVING_FAILED"
};