module.exports = {
    TOGGLE_EDIT: "TOGGLE_EDIT",
    TOGGLE_HIGHLIGHT: "TOGGLE_HIGHLIGHT",
    UPDATE_PIECE: "UPDATE_PIECE",
    ADD_PIECE: "ADD_PIECE",
    STAND_UP: "STAND_UP",

    SAVING_PIECE: "SAVING_PIECE",
    PIECE_SAVED: "PIECE_SAVED",
    PIECE_SAVING_FAILED: "PIECE_SAVING_FAILED"
};